trigger:
  branches:
      include:
        - main
stages:
  - stage: Build
    jobs:
      - job: BuildApp
        pool:
          vmImage: ubuntu-latest
          steps:
            - task: DockerCompose@0
              displayName: 'Build services'
              inputs:
                containerregistrytype: 'Azure Container Registry'
                azureSubscription: 'Azure Connection'
                azureContainerRegistry: 'pfetotalenergies.azurecr.io'
                dockerComposeFile: 'docker-compose.yml'
                dockerComposeFileArgs: 'DOCKER_BUILD_SOURCE='
                action: 'Build services'
                additionalImageTags: '$(Build.BuildId)'
            - task: DockerCompose@0
              displayName: Push services
              inputs:
                containerregistrytype: 'Azure Container Registry'
                azureSubscription: 'Azure Connection'
                azureContainerRegistry: 'pfetotalenergies.azurecr.io'
                dockerComposeFile: 'docker-compose.yml'
                dockerComposeFileArgs: 'DOCKER_BUILD_SOURCE='
                action: 'Push services'
                additionalImageTags: '$(Build.BuildId)'
            - task: CopyFiles@2
              displayName: 'Copy Files'
              inputs:
                Contents: |
                  **/mhc-aks.yaml
                TargetFolder: '$(Build.ArtifactStagingDirectory)'
            - task: PublishBuildArtifacts@1
              displayName: 'Publish Artifact'
              inputs:
                ArtifactName: deploy